export const LOAD_OFFER_PRODUCTS = 'LOAD_OFFER_PRODUCTS';
export const LOAD_WITHOUT_OFFER_PRODUCTS = 'LOAD_WITHOUT_OFFER_PRODUCTS';
export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const UPDATE_PRODUCT_QUANTITY = 'UPDATE_PRODUCT_QUANTITY';